version: '3.9'

services:

  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    # ports:
    #   - 2717:27017
    volumes:
      - mongo_db:/data/db

  api:
    build: .
    ports:
      - 3000:5000
    environment:
      PORT: 5000
      MONGO_DB_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}